import FeatureGallery from "@/components/home/FeatureGallery";
import FeaturesBlocks from "@/components/home/FeaturesBlocks";
import FeaturesFaq from "@/components/home/FeaturesFaq";
import FeaturesMain from "@/components/home/FeaturesMain";
import Target from "@/components/home/Target";
import Hero from "@/components/home/hero";
import { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
  title: "Home - Business",
  description: "Generated by create next app",
};

type Props = {};

function Home({}: Props) {
  return (
    <>
      <Hero />
      <FeaturesBlocks />
      <FeaturesMain />
      <FeaturesFaq />
      <FeatureGallery />
      <Target />
    </>
  );
}

export default Home;
