import FeaturesBlocks from "@/components/home/FeaturesBlocks";
import Hero from "@/components/home/hero";
import { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
  title: "Home - Business",
  description: "Generated by create next app",
};

type Props = {};

function Home({}: Props) {
  return (
    <>
      <Hero />
      <FeaturesBlocks />
    </>
  );
}

export default Home;
